/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LivesRouteImport } from './routes/lives'
import { Route as IslandRouteImport } from './routes/island'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsAgentIdRouteRouteImport } from './routes/agents/$agentId/route'
import { Route as AgentsAgentIdIndexRouteImport } from './routes/agents/$agentId/index'
import { Route as AgentsAgentIdTimelineRouteImport } from './routes/agents/$agentId/timeline'
import { Route as AgentsAgentIdRoomRouteImport } from './routes/agents/$agentId/room'
import { Route as AgentsAgentIdPortfolioRouteImport } from './routes/agents/$agentId/portfolio'
import { Route as AgentsAgentIdPersonalityRouteImport } from './routes/agents/$agentId/personality'
import { Route as AgentsAgentIdFeedRouteImport } from './routes/agents/$agentId/feed'
import { Route as AgentsAgentIdEssaysRouteImport } from './routes/agents/$agentId/essays'
import { Route as AgentsAgentIdBrainRouteImport } from './routes/agents/$agentId/brain'

const LivesRoute = LivesRouteImport.update({
  id: '/lives',
  path: '/lives',
  getParentRoute: () => rootRouteImport,
} as any)
const IslandRoute = IslandRouteImport.update({
  id: '/island',
  path: '/island',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRouteRoute = AgentsAgentIdRouteRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdIndexRoute = AgentsAgentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsAgentIdRouteRoute,
} as any)
const AgentsAgentIdTimelineRoute = AgentsAgentIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AgentsAgentIdRouteRoute,
} as any)
const AgentsAgentIdRoomRoute = AgentsAgentIdRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AgentsAgentIdRouteRoute,
} as any)
const AgentsAgentIdPortfolioRoute = AgentsAgentIdPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AgentsAgentIdRouteRoute,
} as any)
const AgentsAgentIdPersonalityRoute =
  AgentsAgentIdPersonalityRouteImport.update({
    id: '/personality',
    path: '/personality',
    getParentRoute: () => AgentsAgentIdRouteRoute,
  } as any)
const AgentsAgentIdFeedRoute = AgentsAgentIdFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AgentsAgentIdRouteRoute,
} as any)
const AgentsAgentIdEssaysRoute = AgentsAgentIdEssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => AgentsAgentIdRouteRoute,
} as any)
const AgentsAgentIdBrainRoute = AgentsAgentIdBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AgentsAgentIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/island': typeof IslandRoute
  '/lives': typeof LivesRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteRouteWithChildren
  '/agents/$agentId/brain': typeof AgentsAgentIdBrainRoute
  '/agents/$agentId/essays': typeof AgentsAgentIdEssaysRoute
  '/agents/$agentId/feed': typeof AgentsAgentIdFeedRoute
  '/agents/$agentId/personality': typeof AgentsAgentIdPersonalityRoute
  '/agents/$agentId/portfolio': typeof AgentsAgentIdPortfolioRoute
  '/agents/$agentId/room': typeof AgentsAgentIdRoomRoute
  '/agents/$agentId/timeline': typeof AgentsAgentIdTimelineRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/island': typeof IslandRoute
  '/lives': typeof LivesRoute
  '/agents/$agentId/brain': typeof AgentsAgentIdBrainRoute
  '/agents/$agentId/essays': typeof AgentsAgentIdEssaysRoute
  '/agents/$agentId/feed': typeof AgentsAgentIdFeedRoute
  '/agents/$agentId/personality': typeof AgentsAgentIdPersonalityRoute
  '/agents/$agentId/portfolio': typeof AgentsAgentIdPortfolioRoute
  '/agents/$agentId/room': typeof AgentsAgentIdRoomRoute
  '/agents/$agentId/timeline': typeof AgentsAgentIdTimelineRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/island': typeof IslandRoute
  '/lives': typeof LivesRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteRouteWithChildren
  '/agents/$agentId/brain': typeof AgentsAgentIdBrainRoute
  '/agents/$agentId/essays': typeof AgentsAgentIdEssaysRoute
  '/agents/$agentId/feed': typeof AgentsAgentIdFeedRoute
  '/agents/$agentId/personality': typeof AgentsAgentIdPersonalityRoute
  '/agents/$agentId/portfolio': typeof AgentsAgentIdPortfolioRoute
  '/agents/$agentId/room': typeof AgentsAgentIdRoomRoute
  '/agents/$agentId/timeline': typeof AgentsAgentIdTimelineRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/island'
    | '/lives'
    | '/agents/$agentId'
    | '/agents/$agentId/brain'
    | '/agents/$agentId/essays'
    | '/agents/$agentId/feed'
    | '/agents/$agentId/personality'
    | '/agents/$agentId/portfolio'
    | '/agents/$agentId/room'
    | '/agents/$agentId/timeline'
    | '/agents/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/island'
    | '/lives'
    | '/agents/$agentId/brain'
    | '/agents/$agentId/essays'
    | '/agents/$agentId/feed'
    | '/agents/$agentId/personality'
    | '/agents/$agentId/portfolio'
    | '/agents/$agentId/room'
    | '/agents/$agentId/timeline'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/island'
    | '/lives'
    | '/agents/$agentId'
    | '/agents/$agentId/brain'
    | '/agents/$agentId/essays'
    | '/agents/$agentId/feed'
    | '/agents/$agentId/personality'
    | '/agents/$agentId/portfolio'
    | '/agents/$agentId/room'
    | '/agents/$agentId/timeline'
    | '/agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IslandRoute: typeof IslandRoute
  LivesRoute: typeof LivesRoute
  AgentsAgentIdRouteRoute: typeof AgentsAgentIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lives': {
      id: '/lives'
      path: '/lives'
      fullPath: '/lives'
      preLoaderRoute: typeof LivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/island': {
      id: '/island'
      path: '/island'
      fullPath: '/island'
      preLoaderRoute: typeof IslandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/': {
      id: '/agents/$agentId/'
      path: '/'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AgentsAgentIdIndexRouteImport
      parentRoute: typeof AgentsAgentIdRouteRoute
    }
    '/agents/$agentId/timeline': {
      id: '/agents/$agentId/timeline'
      path: '/timeline'
      fullPath: '/agents/$agentId/timeline'
      preLoaderRoute: typeof AgentsAgentIdTimelineRouteImport
      parentRoute: typeof AgentsAgentIdRouteRoute
    }
    '/agents/$agentId/room': {
      id: '/agents/$agentId/room'
      path: '/room'
      fullPath: '/agents/$agentId/room'
      preLoaderRoute: typeof AgentsAgentIdRoomRouteImport
      parentRoute: typeof AgentsAgentIdRouteRoute
    }
    '/agents/$agentId/portfolio': {
      id: '/agents/$agentId/portfolio'
      path: '/portfolio'
      fullPath: '/agents/$agentId/portfolio'
      preLoaderRoute: typeof AgentsAgentIdPortfolioRouteImport
      parentRoute: typeof AgentsAgentIdRouteRoute
    }
    '/agents/$agentId/personality': {
      id: '/agents/$agentId/personality'
      path: '/personality'
      fullPath: '/agents/$agentId/personality'
      preLoaderRoute: typeof AgentsAgentIdPersonalityRouteImport
      parentRoute: typeof AgentsAgentIdRouteRoute
    }
    '/agents/$agentId/feed': {
      id: '/agents/$agentId/feed'
      path: '/feed'
      fullPath: '/agents/$agentId/feed'
      preLoaderRoute: typeof AgentsAgentIdFeedRouteImport
      parentRoute: typeof AgentsAgentIdRouteRoute
    }
    '/agents/$agentId/essays': {
      id: '/agents/$agentId/essays'
      path: '/essays'
      fullPath: '/agents/$agentId/essays'
      preLoaderRoute: typeof AgentsAgentIdEssaysRouteImport
      parentRoute: typeof AgentsAgentIdRouteRoute
    }
    '/agents/$agentId/brain': {
      id: '/agents/$agentId/brain'
      path: '/brain'
      fullPath: '/agents/$agentId/brain'
      preLoaderRoute: typeof AgentsAgentIdBrainRouteImport
      parentRoute: typeof AgentsAgentIdRouteRoute
    }
  }
}

interface AgentsAgentIdRouteRouteChildren {
  AgentsAgentIdBrainRoute: typeof AgentsAgentIdBrainRoute
  AgentsAgentIdEssaysRoute: typeof AgentsAgentIdEssaysRoute
  AgentsAgentIdFeedRoute: typeof AgentsAgentIdFeedRoute
  AgentsAgentIdPersonalityRoute: typeof AgentsAgentIdPersonalityRoute
  AgentsAgentIdPortfolioRoute: typeof AgentsAgentIdPortfolioRoute
  AgentsAgentIdRoomRoute: typeof AgentsAgentIdRoomRoute
  AgentsAgentIdTimelineRoute: typeof AgentsAgentIdTimelineRoute
  AgentsAgentIdIndexRoute: typeof AgentsAgentIdIndexRoute
}

const AgentsAgentIdRouteRouteChildren: AgentsAgentIdRouteRouteChildren = {
  AgentsAgentIdBrainRoute: AgentsAgentIdBrainRoute,
  AgentsAgentIdEssaysRoute: AgentsAgentIdEssaysRoute,
  AgentsAgentIdFeedRoute: AgentsAgentIdFeedRoute,
  AgentsAgentIdPersonalityRoute: AgentsAgentIdPersonalityRoute,
  AgentsAgentIdPortfolioRoute: AgentsAgentIdPortfolioRoute,
  AgentsAgentIdRoomRoute: AgentsAgentIdRoomRoute,
  AgentsAgentIdTimelineRoute: AgentsAgentIdTimelineRoute,
  AgentsAgentIdIndexRoute: AgentsAgentIdIndexRoute,
}

const AgentsAgentIdRouteRouteWithChildren =
  AgentsAgentIdRouteRoute._addFileChildren(AgentsAgentIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IslandRoute: IslandRoute,
  LivesRoute: LivesRoute,
  AgentsAgentIdRouteRoute: AgentsAgentIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
